### ISSUE TITLE
MultiGPU errors

### ISSUE THREAD

**Issue by ebartrum** [NVlabs/stylegan3#101]
Thanks for the great repo!
Training is working fine for me with 1 GPU but I'm getting mysterious errors with >1 GPU. I'm not sure how to fix these. 

When running:  `CUDA_LAUNCH_BLOCKING=1 python train.py --outdir=~/training-runs --cfg=stylegan3-t --data=/home/ed/datasets/birds256.zip  --gpus=4 --batch=8 --gamma=8.2 --mirror=1 --mbstd-group=2`

I get the following output to std out:

```
...
Setting up augmentation...
Distributing across 4 GPUs...
Setting up training phases...
Exporting sample images...

Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 98, in launch_training
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(c, temp_dir), nprocs=c.num_gpus)
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ed/Documents/repos/stylegan3/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/home/ed/Documents/repos/stylegan3/training/training_loop.py", line 287, in training_loop
    torch.distributed.all_reduce(flat)
  File "/home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1285, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:45, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
```

And the following error output:

```
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: the launch timed out and was terminated
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f84d274dd62 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1c5f3 (0x7f8515dfa5f3 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a2 (0x7f8515dfb002 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0xa4 (0x7f84d2737314 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x29adb9 (0x7f8599117db9 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xae0c91 (0x7f859995dc91 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x292 (0x7f859995df92 in /home/ed/.conda/envs/pg/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0xe9cdf (0x5599e80bfcdf in /home/ed/.conda/envs/pg/bin/python)
frame #8: <unknown function> + 0xeb91b (0x5599e80c191b in /home/ed/.conda/envs/pg/bin/python)
frame #9: <unknown function> + 0x2322ab (0x5599e82082ab in /home/ed/.conda/envs/pg/bin/python)
frame #10: <unknown function> + 0xebae3 (0x5599e80c1ae3 in /home/ed/.conda/envs/pg/bin/python)
frame #11: <unknown function> + 0x189bc5 (0x5599e815fbc5 in /home/ed/.conda/envs/pg/bin/python)
frame #12: <unknown function> + 0xebaef (0x5599e80c1aef in /home/ed/.conda/envs/pg/bin/python)
frame #13: <unknown function> + 0x189bc5 (0x5599e815fbc5 in /home/ed/.conda/envs/pg/bin/python)
frame #14: <unknown function> + 0xec098 (0x5599e80c2098 in /home/ed/.conda/envs/pg/bin/python)
frame #15: <unknown function> + 0xee748 (0x5599e80c4748 in /home/ed/.conda/envs/pg/bin/python)
frame #16: <unknown function> + 0xee79b (0x5599e80c479b in /home/ed/.conda/envs/pg/bin/python)
frame #17: <unknown function> + 0xee79b (0x5599e80c479b in /home/ed/.conda/envs/pg/bin/python)
frame #18: <unknown function> + 0xf0142 (0x5599e80c6142 in /home/ed/.conda/envs/pg/bin/python)
frame #19: <unknown function> + 0xebf08 (0x5599e80c1f08 in /home/ed/.conda/envs/pg/bin/python)
frame #20: <unknown function> + 0x1e3af3 (0x5599e81b9af3 in /home/ed/.conda/envs/pg/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x2713 (0x5599e819a213 in /home/ed/.conda/envs/pg/bin/python)
frame #22: _PyEval_EvalCodeWithName + 0x2c3 (0x5599e817ba33 in /home/ed/.conda/envs/pg/bin/python)
frame #23: _PyFunction_Vectorcall + 0x378 (0x5599e817ce18 in /home/ed/.conda/envs/pg/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0xa63 (0x5599e8198563 in /home/ed/.conda/envs/pg/bin/python)
frame #25: _PyFunction_Vectorcall + 0x1a6 (0x5599e817cc46 in /home/ed/.conda/envs/pg/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x947 (0x5599e8198447 in /home/ed/.conda/envs/pg/bin/python)
frame #27: _PyEval_EvalCodeWithName + 0x2c3 (0x5599e817ba33 in /home/ed/.conda/envs/pg/bin/python)
frame #28: _PyFunction_Vectorcall + 0x378 (0x5599e817ce18 in /home/ed/.conda/envs/pg/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x1824 (0x5599e8199324 in /home/ed/.conda/envs/pg/bin/python)
frame #30: _PyEval_EvalCodeWithName + 0x2c3 (0x5599e817ba33 in /home/ed/.conda/envs/pg/bin/python)
frame #31: PyEval_EvalCodeEx + 0x39 (0x5599e817ca99 in /home/ed/.conda/envs/pg/bin/python)
frame #32: PyEval_EvalCode + 0x1b (0x5599e82251db in /home/ed/.conda/envs/pg/bin/python)
frame #33: <unknown function> + 0x24f273 (0x5599e8225273 in /home/ed/.conda/envs/pg/bin/python)
frame #34: <unknown function> + 0x26cea3 (0x5599e8242ea3 in /home/ed/.conda/envs/pg/bin/python)
frame #35: PyRun_StringFlags + 0x7d (0x5599e8247ccd in /home/ed/.conda/envs/pg/bin/python)
frame #36: PyRun_SimpleStringFlags + 0x3d (0x5599e8247d2d in /home/ed/.conda/envs/pg/bin/python)
frame #37: Py_RunMain + 0x158 (0x5599e8248ac8 in /home/ed/.conda/envs/pg/bin/python)
frame #38: Py_BytesMain + 0x39 (0x5599e8248e99 in /home/ed/.conda/envs/pg/bin/python)
frame #39: __libc_start_main + 0xd5 (0x7f859bd6eb25 in /usr/lib/libc.so.6)
frame #40: <unknown function> + 0x1dcd1d (0x5599e81b2d1d in /home/ed/.conda/envs/pg/bin/python)

/home/ed/.conda/envs/pg/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 17 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Any ideas on how to fix this?

**Comment by ebartrum** [comment]
OK I seem to have resolved this now. It seems the problem was caused by having an X session running during training. I hadn't realised this doesn't work! For some reason, training other models on all gpus with pytorch lightning while running an X session was fine. Hope someone else who has this problem comes across this issue!

**Comment by MationPlays** [comment]
> OK I seem to have resolved this now. It seems the problem was caused by having an X session running during training. I hadn't realised this doesn't work! For some reason, training other models on all gpus with pytorch lightning while running an X session was fine. Hope someone else who has this problem comes across this issue!

have you managed to implement stylegan3 into lightning? Do you have a repo for this? This would be great!

**Comment by ebartrum** [comment]
> > OK I seem to have resolved this now. It seems the problem was caused by having an X session running during training. I hadn't realised this doesn't work! For some reason, training other models on all gpus with pytorch lightning while running an X session was fine. Hope someone else who has this problem comes across this issue!
> 
> have you managed to implement stylegan3 into lightning? Do you have a repo for this? This would be great!

I managed to put SG2 into lightning, as part of a larger project which should be made public in the coming months! There are a couple of public implementations of SG2 in lightning, but they didn't work for me. I'll probably be trying to put SG3 into it at some point.

**Comment by MationPlays** [comment]
> > > OK I seem to have resolved this now. It seems the problem was caused by having an X session running during training. I hadn't realised this doesn't work! For some reason, training other models on all gpus with pytorch lightning while running an X session was fine. Hope someone else who has this problem comes across this issue!
> > 
> > 
> > have you managed to implement stylegan3 into lightning? Do you have a repo for this? This would be great!
> 
> I managed to put SG2 into lightning, as part of a larger project which should be made public in the coming months! There are a couple of public implementations of SG2 in lightning, but they didn't work for me. I'll probably be trying to put SG3 into it at some point.

Then good luck with st3. I am new to lightning and can't really get my head around how to implement it into lightning. Would you have some links to these public ones? I only found one which is not good imo: https://github.com/duskvirkus/stylegan2-ada-lightning
